//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::UnityEngine.Experimental.Rendering.Universal.RenderObjects.RenderObjectsSettings))]
	public class PropertyProvider_UnityEngine_Experimental_Rendering_Universal_RenderObjects_RenderObjectsSettings : Unity.VisualScripting.SerializedPropertyProvider<UnityEngine.Experimental.Rendering.Universal.RenderObjects.RenderObjectsSettings>
	{
	}
}
